name = "Mini Create"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08129713f311dad1cbc781eeed6ea0edfb3f0247cada417881f9b4d4cc7a3dcd"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
