name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21565a5f9c3ee4e7b07f1b6c420a96ab914fc91ffc84897671f4395051691032"

[versions]
forge = "43.1.32"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
