name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f2f402dd39db9b974ed5ab1b94541fdb0298e3f29c528663b23906015e18637"

[versions]
forge = "43.1.43"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
