name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a913e5253628fb68a2e99e1556142ffc57f5456e824f65e609179c0dc57edcf"

[versions]
forge = "43.1.33"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
