name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5077d197513a533076b3711513de69f2eaf6fa3095dc01b69a4b373bec2cc5e6"

[versions]
forge = "43.1.43"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
