name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a85adcde2492198cadd90664850247b26cec654f66ae7a81046a9fb9e4431ff"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
