name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "522f8117c3c87c622ff4537a43ed147e3e52ffb5d3c01fe45c71bc4f96d68a5e"

[versions]
forge = "43.1.47"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
