name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5474e06352c0a6e8f88f40b90824b70b7e96162695a175333d723cef7ce5267"

[versions]
forge = "43.1.47"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
