name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "531f440ba3452282abb283a3a14a3acd414bc8f172af8b444eb53208a5f46742"

[versions]
forge = "43.1.32"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
