name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "092cc45c659b75ea9f7adc04e3c81de3f175fb7354260c90227cef9e7aded445"

[versions]
forge = "43.2.4"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
