name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70e5d47a4f50b8472c283e05a1ec41b65b9eb0c2c3a7aa89847b0f08afd04bbb"

[versions]
forge = "43.1.47"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
