name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "769890245b69eaeba1572f498ffe0c7be0cc8866976812777bb3f82bb40e3ed3"

[versions]
forge = "43.1.33"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
