name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eccdf69525bfb755f23662d2ab5c569a9d20f8378de3d1209d2f07316441f73f"

[versions]
forge = "43.1.1"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
