name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde851cb57a295532c5bd2ffbed94141a218d2594c261ccd9f78c001dcf0286f"

[versions]
forge = "43.1.47"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
