name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f26f00652a15d96ac92c794a9f4e440776857fc9e36abbd375b9e1c1f30f960"

[versions]
forge = "43.1.33"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
