name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb42a5b9ed469c1aec83a95d383ba3befff73f3ef9e283f334ed70aaec0a7b6"

[versions]
forge = "43.1.33"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
