name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25ffb2b0fb5bdbefa5ad2b56636a5dd00dee9f7724d3db02994385a1cfcaad4a"

[versions]
forge = "43.1.43"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
