name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e690245a1bed41aa79b18846780bcb48345b6f7a14482849cb1adf68afca246"

[versions]
forge = "43.1.47"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
