name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1fe07da661588fa1070a022f9b2a58fcd3508339bd9e56778bdc7c96229ccb6"

[versions]
forge = "43.1.32"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
