name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c03e53cfdeb4bf1ef85347f3297b39b49d3c51475129f9e1bbed676507f9bcaa"

[versions]
forge = "43.1.33"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
