name = "Create Minecolonies"
author = "appkins"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1874b353c8148fd398bd7694edba719e33d8e5757f2198af0f1eb72cfdb3052"

[versions]
forge = "43.1.32"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
