name = "Create Micro"
author = "Appkins"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a16b30f0a3804ffc52fc115ec2d785fa36a2040409025d2c635e93bd9cbffb3"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
