name = "Create Micro"
author = "Appkins"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11c3fef564a85bbf171a4c4705f92c8ff8108db56b9bf79e14c645a056e556b7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
