name = "Additive"
author = "UltraStorm"
version = "1.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d91b7edb94b7544d2e708c314cac30f84557647c89534dd341a2a0ab6cb88d5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
