name = "Create Micro"
author = "Appkins"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce34ff14b0db6e73b0ee94f4291c4b61b999837bc034493751096f869935c470"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
